spring:
  application:
    name: covoiturage

  datasource:
    url: jdbc:postgresql://10.11.31.98:5432/covoiturage
    username: covoiturage
    password: covoiturage

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true


server:
  port: 8080

app:
  jwt:
    secret: ${JWT_SECRET:dev-secret-a-remplacer-32-caracteres-minimum-svp}
    expiration-ms: 86400000   # 24 heures
  cors:
    allowed-origins: http://10.11.31.98:5173
